name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_PROD_ID }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (production or preview)'
        required: true
        default: 'production'

jobs:
  Deploy-Vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes \
            --environment=${{ github.event.inputs.environment }} \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: ${{ github.event.inputs.environment == 'preview' }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy \
            --${{ github.event.inputs.environment == 'production' && 'prod' || 'prebuilt' }} \
            --token=${{ secrets.VERCEL_TOKEN }}
